# Generated by Django 5.2.15 on 2026-08-15 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0002_lessonprogress"),
    ]

    operations = [
        migrations.AddField(
            model_name="lessontranslation",
            name="content_html",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="lessontranslation",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="moduletranslation",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
