# Generated by Django 5.2.15 on 2026-08-14 17:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("site", "0002_site_i18n"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="bunny_api_key",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="bunny_cdn_hostname",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="bunny_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="bunny_library_id",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="bunny_token_key",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="bunny_token_ttl_seconds",
            field=models.PositiveIntegerField(default=3600),
        ),
    ]
