# Generated by Django 5.2.15 on 2026-08-14 17:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("site", "0003_sitesettings_bunny_api_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="stripe_cancel_url",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="stripe_currency",
            field=models.CharField(default="eur", max_length=3),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="stripe_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="stripe_mode",
            field=models.CharField(default="test", max_length=10),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="stripe_publishable_key",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="stripe_secret_key",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="stripe_success_url",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="stripe_webhook_secret",
            field=models.TextField(blank=True),
        ),
    ]
