# Generated by Django 5.2.15 on 2026-08-14 19:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("site", "0004_sitesettings_stripe_cancel_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="newslettersubscriber",
            name="consent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="newslettersubscriber",
            name="consented_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="newslettersubscriber",
            name="extra_tags",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="newslettersubscriber",
            name="language",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="newslettersubscriber",
            name="mailchimp_audience_id",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="newslettersubscriber",
            name="mailchimp_audience_name",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="newslettersubscriber",
            name="mailchimp_error",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="newslettersubscriber",
            name="mailchimp_group",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="newslettersubscriber",
            name="mailchimp_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendiente"),
                    ("synced", "Sincronizado"),
                    ("failed", "Error"),
                    ("skipped", "Omitido"),
                ],
                default="skipped",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="newslettersubscriber",
            name="mailchimp_synced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="newslettersubscriber",
            name="mailchimp_tags",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="newslettersubscriber",
            name="name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="mailchimp_api_key",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="mailchimp_audience_id",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="mailchimp_audience_name",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="mailchimp_double_opt_in",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="mailchimp_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="mailchimp_from_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="mailchimp_from_name",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="mailchimp_interest_es_id",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="mailchimp_interest_sk_id",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="mailchimp_language_category_id",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="mailchimp_marketing_permission_ids",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="mailchimp_transactional_api_key",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="mailchimp_web_tag_es",
            field=models.CharField(default="WEB_ES", max_length=40),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="mailchimp_web_tag_sk",
            field=models.CharField(default="WEB_SK", max_length=40),
        ),
    ]
