# Generated by Django 5.2.15 on 2026-08-14 23:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("site", "0005_mailchimp_and_newsletter_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="google_client_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="google_client_secret",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="google_oauth_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
