# Generated by Django 5.2.15 on 2026-08-17 15:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("site", "0006_google_oauth_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettingstranslation",
            name="contracting_html",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="sitesettingstranslation",
            name="contracting_title",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="sitesettingstranslation",
            name="privacy_html",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="sitesettingstranslation",
            name="privacy_title",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="sitesettingstranslation",
            name="terms_html",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="sitesettingstranslation",
            name="terms_title",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
