# Generated by Django 5.2.15 on 2026-08-18 16:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("commerce", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("started", "Iniciado"),
                            ("succeeded", "Correcto"),
                            ("failed", "Fallido"),
                            ("expired", "Expirado"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="eur", max_length=3)),
                ("customer_email", models.EmailField(blank=True, max_length=254)),
                ("stripe_session_id", models.CharField(blank=True, max_length=255)),
                ("stripe_payment_intent", models.CharField(blank=True, max_length=255)),
                (
                    "stripe_event_id",
                    models.CharField(blank=True, max_length=255, null=True, unique=True),
                ),
                ("stripe_event_type", models.CharField(blank=True, max_length=120)),
                ("failure_code", models.CharField(blank=True, max_length=80)),
                ("failure_message", models.TextField(blank=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_attempts",
                        to="commerce.order",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_attempts",
                        to="accounts.useraccount",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
