# Generated by Django 5.2.15 on 2026-08-14 17:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="bunny_video_id",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
