# Generated by Django 5.2.15 on 2026-08-15 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_recipe_bunny_video_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipetranslation",
            name="ingredients_html",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="recipetranslation",
            name="preparation_html",
            field=models.TextField(blank=True),
        ),
    ]
