# Generated by Django 5.2.15 on 2026-08-17 15:32

import apps.catalog.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0003_rich_text_translations"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="event_address",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="course",
            name="event_starts_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="format",
            field=models.CharField(
                choices=[("online", "Online"), ("in_person", "Presencial")],
                default="online",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="maps_url",
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.CreateModel(
            name="CourseResource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("pdf", "PDF"), ("image", "Imagen"), ("file", "Archivo")],
                        default="file",
                        max_length=16,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        max_length=255,
                        upload_to=apps.catalog.models.course_resource_upload_path,
                    ),
                ),
                ("original_name", models.CharField(blank=True, max_length=255)),
                ("content_type", models.CharField(blank=True, max_length=120)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="catalog.course",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="CourseResourceTranslation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="course_resource_translations",
                        to="catalog.language",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="catalog.courseresource",
                    ),
                ),
            ],
            options={
                "ordering": ["language__code"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("resource", "language"),
                        name="uniq_course_resource_translation_lang",
                    )
                ],
            },
        ),
    ]
